-- 1.Create Employees tables
CREATE TABLE EMPLOYEES
   (	Employee_ID NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY, 
	Employee_Name VARCHAR2(50) NOT NULL, 
        Job_Title VARCHAR2(50) NOT NULL, 
        Manger_ID NUMBER(10,0),
	Date_Hired date NOT NULL,
        Salary NUMBER(10) NOT NULL,
        Department_id NUMBER(5,0) NOT NULL,
	CONSTRAINT EMPLOYEES_ID_PK1 PRIMARY KEY (Employee_ID),
   CONSTRAINT Department_id_FK
    FOREIGN KEY (Department_id)
     REFERENCES Department(Department_id)
     ON DELETE CASCADE
);

/

--- Creating history table for audit purpose
CREATE TABLE  EMPLOYEES_history 
   (	Employee_ID NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY, 
	Emploee_Name VARCHAR2(50) NOT NULL, 
        Job_Title VARCHAR2(50) NOT NULL, 
        Manger_ID NUMBER(10,0),
	Date_Hired date NOT NULL,
        Salary NUMBER(10,0) NOT NULL,
        Department_id NUMBER(5,0) NOT NULL,
	CONSTRAINT EMPLOYEES_ID_PK PRIMARY KEY (Employee_ID )
);

--Here if required we can partition employee table either by Department_id(List) or salary(range)

/

CREATE TABLE Department 
   (	Department_id  NUMBER(5,0) GENERATED BY DEFAULT AS IDENTITY,   
	Department_NAME VARCHAR2(50) NOT NULL, 
	Location VARCHAR2(50) NOT NULL, 
	CONSTRAINT Department_id_PK PRIMARY KEY (Department_id )
 
   );
/
---If required we can have History table